export interface TraitCategory {
  id: string
  label: string
  labelZh: string
  folder: string
  items: string[]
}

export const TRAIT_CATEGORIES: TraitCategory[] = [
  {
    id: "backgrounds",
    label: "Background",
    labelZh: "背景",
    folder: "backgrounds",
    items: [
      "arena scalibur.png",
      "barrenlands fishing spot.png",
      "BG grass.png",
      "BG pebblestones.png",
      "capital city portal.png",
      "duel statue.png",
      "fishing spot.png",
      "lodestones.png",
      "ruined dungeon entrance.png",
      "shroom altar.png",
      "stairs.png",
    ],
  },
  {
    id: "skins",
    label: "Skin",
    labelZh: "皮肤",
    folder: "skins",
    items: [
      "1.png",
      "2.png",
      "3.png",
      "4.png",
      "5.png",
      "6.png",
      "7.png",
      "8.png",
      "9.png",
      "10.png",
    ],
  },
  {
    id: "hair",
    label: "Hair",
    labelZh: "发型",
    folder: "hair",
    items: [
      "black (f).png",
      "black (m).png",
      "blonde (f).png",
      "blonde (m).png",
      "blue (f).png",
      "blue (m).png",
      "brown (f).png",
      "brown (m).png",
      "pink (f).png",
      "pink (m).png",
      "white (f).png",
      "white (m).png",
    ],
  },
  {
    id: "armor",
    label: "Armor",
    labelZh: "护甲",
    folder: "armor",
    items: [
      "Adamantine Chain Armor.png",
      "Adamantine Plate Armor.png",
      "Bearhide Leather Armor.png",
      "bronze chain armor.png",
      "bronze plate armor.png",
      "Dragonsteel Armor.png",
      "Enchanted Robes.png",
      "Mystic Robes.png",
      "Nightmare Robes.png",
      "Obsidian Armor.png",
      "Rogue's Rags.png",
      "steel chain armor.png",
      "steel plate armor.png",
    ],
  },
  {
    id: "head",
    label: "Head",
    labelZh: "头部",
    folder: "head",
    items: [
      "abstract wizard hat.png",
      "Adamantine full helm.png",
      "aether mage wizard hat.png",
      "blast wizard hood.png",
      "bronze full helm.png",
      "Crownlands full helm.png",
      "cultist hood.png",
      "Dragonsteel Helm.png",
      "Eite Crownlands helm.png",
      "elite magic hood.png",
      "ghostly hood.png",
      "green party hat.png",
      "HEAD moggles.png",
      "Obsidian helm.png",
      "party hat.png",
      "purple party hat.png",
      "red party hat.png",
      "red wizard hat.png",
      "robin hood hat.png",
      "Rogue's Headband.png",
      "steel full helm.png",
      "wizard hat.png",
      "angel halo.png",
      "wifhat.png",
    ],
  },
  {
    id: "weapon",
    label: "Weapon",
    labelZh: "武器",
    folder: "weapon",
    items: [
      "adamantine battle axe.png",
      "Adamantine dagger.png",
      "Adamantine falchion.png",
      "adamantine spear.png",
      "Adamantine Sword.png",
      "archmage staff.png",
      "battle axe.png",
      "bronze dagger.png",
      "bronze sword.png",
      "crossbow.png",
      "Cultist's Repeater.png",
      "dragonsteel dagger.png",
      "Dragonsteel falchion.png",
      "Dragonsteel Sword.png",
      "ember rod.png",
      "empowered staff.png",
      "enhanced fishing rod.png",
      "fishing rod.png",
      "iron battle axe.png",
      "iron dagger.png",
      "iron falchion.png",
      "iron spear.png",
      "iron sword.png",
      "longbow.png",
      "Mageslayer Bow.png",
      "Mystbark bow.png",
      "Occultist's Grand Staff.png",
      "pearl rod.png",
      "reinforced crossbow.png",
      "Staff.png",
      "viridian rod.png",
    ],
  },
  {
    id: "objects",
    label: "Object",
    labelZh: "物品",
    folder: "objects",
    items: [
      "artifact.png",
      "black shroom.png",
      "chest.png",
      "coca leaves.png",
      "energy orb.png",
      "Exquisite Artifact .png",
      "Fabled Artifact.png",
      "lever.png",
      "lootbag.png",
      "mushroom pie.png",
      "Otherworldly Artifact.png",
      "red shroom.png",
      "training dummy.png",
      "trout.png",
      "UNHOLY ARTIFACT.png",
      "yellow shroom.png",
    ],
  },
]

export function getTraitDisplayName(filename: string): string {
  return filename.replace(/\.png$/i, "")
}

export function getTraitPath(folder: string, filename: string): string {
  return `/traits/${folder}/${filename}`
}
