export interface TraitCategory {
  id: string
  label: string
  labelZh: string
  folder: string
  items: string[]
}

export const TRAIT_CATEGORIES: TraitCategory[] = [
  {
    id: "backgrounds",
    label: "Background",
    labelZh: "背景",
    folder: "backgrounds",
    items: [
      "arena scalibur.png",
      "barrenlands fishing spot.png",
      "BG grass.png",
      "BG pebblestones.png",
      "capital city portal.png",
      "duel statue.png",
      "fishing spot.png",
      "lodestones.png",
      "ruined dungeon entrance.png",
      "shroom altar.png",
      "stairs.png",
    ],
  },
  {
    id: "skins",
    label: "Skin",
    labelZh: "皮肤",
    folder: "skins",
    items: [
      "1.png",
      "2.png",
      "3.png",
      "4.png",
      "5.png",
      "6.png",
      "7.png",
      "8.png",
      "9.png",
      "10.png",
    ],
  },
  {
    id: "hair",
    label: "Hair",
    labelZh: "发型",
    folder: "hair",
    items: [
      "Benzz Hair.png",
      "black (f).png",
      "black (m).png",
      "blonde (f).png",
      "blonde (m).png",
      "blue (f).png",
      "blue (m).png",
      "brown (f).png",
      "brown (m).png",
      "pink (f).png",
      "pink (m).png",
      "white (f).png",
      "white (m).png",
    ],
  },
  {
    id: "armor",
    label: "Armor",
    labelZh: "护甲",
    folder: "armor",
    items: [
      "Adamantine Chain Armor.png",
      "Adamantine Plate Armor.png",
      "Aether Mage Robe.png",
      "Bearhide Leather Armor.png",
      "Blackwagersuits Clothing.png",
      "bronze chain armor.png",
      "bronze plate armor.png",
      "Catonesie Clothing.png",
      "cyril robes.png",
      "Dogonesie Clothing.png",
      "Dragonsteel Armor.png",
      "Enchanted Robes.png",
      "Highkingsrobes Clothing.png",
      "Highqueensrobes Clothing.png",
      "Mystic Robes.png",
      "Nightmare Robes.png",
      "Obsidian Armor.png",
      "Redwagersuits Clothing.png",
      "reindeer clothes.png",
      "Rogue's Rags.png",
      "Santa Clothing.png",
      "steel chain armor.png",
      "steel plate armor.png",
    ],
  },
  {
    id: "head",
    label: "Head",
    labelZh: "头部",
    folder: "head",
    items: [
      "abstract wizard hat.png",
      "Adamantine full helm.png",
      "Aether Mage Wizard Hat.png",
      "angel halo.png",
      "black halloween mask.png",
      "blast wizard hood.png",
      "bronze full helm.png",
      "Cathoodie.png",
      "clown mask.png",
      "Crownlands full helm.png",
      "cultist hood.png",
      "Doghoodie.png",
      "Dragonsteel Helm.png",
      "Eite Crownlands helm.png",
      "elite magic hood.png",
      "fish mask.png",
      "ghostly hood.png",
      "green halloween mask.png",
      "green party hat.png",
      "HEAD moggles.png",
      "logic mask.png",
      "Obsidian helm.png",
      "party hat.png",
      "pumpkinhead.png",
      "purple party hat.png",
      "queen crown.png",
      "red halloween mask.png",
      "red party hat.png",
      "red wizard hat.png",
      "Redwagertophat.png",
      "reindeer hat.png",
      "robin hood hat.png",
      "Rogue's Headband.png",
      "santa beard .png",
      "Santahatwhite.png",
      "steel full helm.png",
      "wifhat.png",
      "wizard hat.png",
      "white party hat.png",
    ],
  },
  {
    id: "weapon",
    label: "Weapon",
    labelZh: "武器",
    folder: "weapon",
    items: [
      "adamantine battle axe.png",
      "Adamantine dagger.png",
      "Adamantine falchion.png",
      "adamantine spear.png",
      "Adamantine Sword.png",
      "Aether Staff.png",
      "archmage staff.png",
      "battle axe.png",
      "Benzz Coffee.png",
      "bronze dagger.png",
      "bronze sword.png",
      "crossbow.png",
      "Cultist's Repeater.png",
      "cyril sword.png",
      "dragonsteel dagger.png",
      "Dragonsteel falchion.png",
      "Dragonsteel Sword.png",
      "ember rod.png",
      "empowered staff.png",
      "enhanced fishing rod.png",
      "fishing rod.png",
      "iron battle axe.png",
      "iron dagger.png",
      "iron falchion.png",
      "iron spear.png",
      "iron sword.png",
      "longbow.png",
      "Mageslayer Bow.png",
      "Mystbark bow.png",
      "Occultist's Grand Staff.png",
      "pearl rod.png",
      "reinforced crossbow.png",
      "Staff.png",
      "viridian rod.png",
    ],
  },
  {
    id: "objects",
    label: "Object",
    labelZh: "物品",
    folder: "objects",
    items: [
      "artifact.png",
      "black shroom.png",
      "chest.png",
      "coca leaves.png",
      "energy orb.png",
      "Exquisite Artifact .png",
      "Fabled Artifact.png",
      "lever.png",
      "lootbag.png",
      "mushroom pie.png",
      "Otherworldly Artifact.png",
      "red shroom.png",
      "training dummy.png",
      "trout.png",
      "UNHOLY ARTIFACT.png",
      "yellow shroom.png",
    ],
  },
]

export function getTraitDisplayName(filename: string): string {
  return filename.replace(/\.png$/i, "")
}

export function getTraitPath(folder: string, filename: string): string {
  return `/traits/${folder}/${filename}`
}
